### PR TITLE
Upgrade yargs to more recent version

### PR DESCRIPTION
**Pull request by igeligel**
**What**: 

- Upgraded `yargs` dependency

**Why**:

- our local https://snyk.io/ instance was complaining about dependencies with vulnerabilities - upgrading `yargs` would mitigate this.

```
Medium severity vulnerability found in mem

  Description: Denial of Service (DoS)

  Info: https://snyk.io/vuln/npm:mem:20180117

  Introduced through: prettier-eslint-cli@4.7.1

  From: prettier-eslint-cli@4.7.1 > yargs@10.0.3 > os-locale@2.1.0 > mem@1.1.0
```

**How**:

- Bumping the dependency

I do not know why it formatted the `package.json` but I did not run a formatter so it might be a linting rule.

### CODE REVIEW

**Comment by igeligel** [comment]
Hey @j-f1 , Who is responsible for merging this?

For the future, we could add https://dependabot.com/blog/hello-github/ which is now free for GitHub projects and would not even bother so much about dependency updates.

**Comment by zimme** [comment]
Fixed in version 5.0.0

**Comment by igeligel** [comment]
@zimme Thanks a lot :)

Is there a possibility you activate dependabot for this repository?

**Comment by zimme** [comment]
Yeah, I could look into that

**Pull request closed without merging**
