### PR TITLE
Declare indent-string as a production dependency

### PR DESCRIPTION
**Pull request by alubbe**
**What**: Declare indent-string as a production dependency

**Why**: It's used in `src/format-files.js`

**How**:

### CODE REVIEW

**Comment by alubbe** [comment]
could we merge and publish this? yarn 2 keeps complaining ;)

**Comment by kylemh** [comment]
@zimme any idea on why I don't have a way of updating branches with `master`? Wanna make sure this runs in CI.

**Comment by HexMox** [comment]
any updates?

**Comment by kylemh** [comment]
https://github.com/prettier/prettier-eslint-cli/pull/425

**Pull request closed without merging**
