### PR TITLE
feat: :package: Support ESLint 8

### LINKED ISSUE #427: Error after updating eslint to 8.1.0
Hey,

once I update eslint from 7.32.0 to 8.1.0. I see an error on my command line when I run `prettier-eslint`:

Scripts:
```json
"prettier:watch": "onchange \"**/*.+(js|jsx|json|scss|css)\" -- prettier-eslint --write $PWD/{{changed}}",
"prettier:format": "prettier-eslint --write \"src/**/*.+(js|jsx|json|scss|css)\"",
```

My config:

- `prettier-eslint-cli` version: 5.0.1
- `prettier` version: 2.4.1
- `eslint` version: 8.1.0

prettier-eslint shows error:

```sh
prettier-eslint [ERROR]: There was trouble creating the ESLint CLIEngine.
prettier-eslint-cli [ERROR]: There was an error formatting "/Users/me/workspace/company/app/frontend/package.json":
TypeError: CLIEngine is not a constructor
at getESLintCLIEngine (/Users/me/workspace/company/app/frontend/node_modules/prettier-eslint/dist/utils.js:403:12)
at getESLintConfig (/Users/me/workspace/company/app/frontend/node_modules/prettier-eslint/dist/index.js:210:51)
at format (/Users/me/workspace/company/app/frontend/node_modules/prettier-eslint/dist/index.js:75:71)
at MapSubscriber.project (/Users/me/workspace/company/app/frontend/node_modules/prettier-eslint-cli/dist/format-files.js:268:54)
at MapSubscriber._next (/Users/me/workspace/company/app/frontend/node_modules/rxjs/internal/operators/map.js:49:35)
at MapSubscriber.Subscriber.next (/Users/me/workspace/company/app/frontend/node_modules/rxjs/internal/Subscriber.js:66:18)
at AsyncSubject.Subject.next (/Users/me/workspace/company/app/frontend/node_modules/rxjs/internal/Subject.js:60:25)
at AsyncSubject.complete (/Users/me/workspace/company/app/frontend/node_modules/rxjs/internal/AsyncSubject.js:53:35)
at handler (/Users/me/workspace/company/app/frontend/node_modules/rxjs/internal/observable/bindNodeCallback.js:53:33)
at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:69:3)
failure formatting 1 file with prettier-eslint


```

### LINKED ISSUE #428: Still reports "jsxBracketSameLine is deprecated." even when option is not used
- `prettier-eslint-cli` 5.0.1:
- `prettier` 2.5.0:
- `eslint` 7.11.0:

Relevant code/config.

```json
{
    "printWidth": 120,
    "tabWidth": 4,
    "bracketSameLine": false,
    "trailingComma": "es5"
}

```

What you did:
```
prettier-eslint "src/**/*.@(js|ts|jsx|tsx)" "cypress/**/*.@(ts|js)" --write --prettier-last
```

What happened:
I get a warning:
> jsxBracketSameLine is deprecated.

Reproduction:

-- paste your link here --

Problem description:
The program reports the deprecation of the `jsxBracketSameLine` option, which I'm aware of. As you can see from the prettier config above, there is no `jsxBracketSameLine` option being used.

Suggested solution:
This program should respect the config for user-installed prettier and not produce such extraneous warnings.

### PR DESCRIPTION
**Pull request by idahogurl**
Closes #427 
Closes #428

**What**:
BREAKING CHANGE:
Requires ESLint 8. ESLint 8 API changes caused the format function to now be asynchronous.
Requires minimum Node 12 as required by ESLint 8

### CODE REVIEW

**Review by kylemh — APPROVED** [review]
looks good to me! love the energy

**Review by zimme — APPROVED** [review]
LGTM, with 1 comment.

The configuration part might need proper testing to make sure eslint config file merging works properly, etc.

This new `overrideConfigFile` option seems like it will use the provided config file only and not do any kind of merging with parent config files, etc.

**Comment by idahogurl** [comment]
@zimme Good catch! Further testing does need to be done. I just need to either add a test or test it on my own with a sample project.

**Comment by idahogurl** [comment]
Blocked by [prettier/prettier-eslint#745](https://github.com/prettier/prettier-eslint/pull/745/files) to get the `overrideConfigFile` option to work.

**Comment by chrisbobbe** [comment]
Thank you! For the record, this PR fixes

- https://github.com/prettier/prettier-eslint-cli/issues/303
- https://github.com/prettier/prettier-eslint-cli/issues/304

Is that right?

**Comment by idahogurl** [comment]
@chrisbobbe Good catch! 
Closes #303 
Closes #304

**Comment by kylemh** [comment]
what a machine 🎉

**Pull request merged**
