### PR TITLE
[Fixes #52] Add node engines version to package.json

### LINKED ISSUE #52: Requires Node 4, should have engines listed in package.json
I tried installing this in one of our legacy projects, but had a runtime error because there are string templates in the code, and we're still stuck on node 0.12. (Yeah I know, it's ancient.) 

The package.json file should probably have `engines` added to it, so it's enforced that it can't be installed on older node versions.

### PR DESCRIPTION
**Pull request by MikeyBurkman**
Fixes #52 

Pretty sure this is all that's necessary.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Would you like to [add yourself](../blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) to the [contributors table](../#contributors)?

**Comment by kentcdodds** [comment]
Feel free to open another PR to add yourself if you'd like 😀

**Comment by MikeyBurkman** [comment]
Nah it's cool lol. I don't think adding 3 lines to a package.json is really worth "contributor" status lol

**Comment by kentcdodds** [comment]
I disagree. You've done much more than anyone else who's come across this problem. You reported it and even that is worth getting into the table 😀

**Pull request merged**
