### PR TITLE
fix(format-files): ensure paths passed to `prettier-eslint` are absolute paths

### PR DESCRIPTION
**Pull request by dpwilhelmsen**
**What**:

This addresses the error reported in #205 & #208. `Error: 'basePath' should be an absolute path`

**Why**:

As of the 6.7.0 release of eslint, absolute paths are required when eslint is searching for ignore patterns (eslint/eslint@ca3b2a62c9e829dc4534bca3643d6bc729b46df0). This causes prettier-eslint-cli to fail if called with a glob pattern using relative paths. This PR ensures they are always absolute paths.

As an example, this command would fail:
`prettier-eslint --list-different --write "./src/**/*.{js,jsx}"`

To get it working with `eslint@^6.7.0`, you'd have to find a way to ensure the paths are absolute in the glob, like this:

`prettier-eslint --list-different --write "$(pwd)/src/**/*.{js,jsx}"`

This change would make either glob pattern valid.

**How**:

In `format-files.js` the `filePathToFormatted` has been updated to run the `filePath` variable through `path.resolve()` to ensure it is an absolute path before being passed into the `formatFile` method.

### CODE REVIEW

**Comment by jingsam** [comment]
I am waitting for this PR to be merged

**Comment by NicolasRannou** [comment]
Bump :)

**Comment by jjorissen52** [comment]
@kentcdodds What needs to happen for this to be merged?

**Comment by kentcdodds** [comment]
Sorry, I haven't maintained this project for years now. You'll need to find an active maintainer.

**Comment by kemicofa** [comment]
+1 would be nice to get this fixed

**Comment by marcofugaro** [comment]
Looks like this repo is dead

**Pull request merged**
