### PR TITLE
Fix #125 - Validation by removing Prettier `config` prop.

### LINKED ISSUE #125: Unknown option "config" with value "undefined" was found.
- `prettier-eslint-cli` version: 8.8.1
- `prettier` version: 1.10.2
- `eslint` version: 4.17.0

What you did:

```shell
prettier-eslint --write "src/**/*.js"
```

What happened:

```shell
Validation Warning:

  Unknown option "config" with value "undefined" was found.
  This is probably a typing mistake. Fixing it will remove this message.
```

**P.S.** It outputs this warning for every file. It seems that `prettier-eslint-cli` sends unnecessary option `config`  in `prettierOptions`.

### PR DESCRIPTION
**Pull request by ReDrUm**
See #125 for [details](https://github.com/prettier/prettier-eslint-cli/issues/125#issuecomment-363982482).

* Removes the Prettier `config` path prop which fails validation and doesn’t appear to be used (yet?).
* Adds eslint ignore to existing method which fails validation due to eslint complexity rule.

### CODE REVIEW

**Comment by ReDrUm** [comment]
By the way the formatting of the contributors table became malformed when auto-generating via `yarn start contributors.add`. I manually updated it for this PR.

**Comment by neilsh** [comment]
May also need to modify the README to remove the `--config` reference, https://github.com/prettier/prettier-eslint-cli/pull/104

**Comment by zimme** [comment]
Thanks for this guys. I hope I have some time this weekend to look at this and hopefully merge.

**Comment by neilsh** [comment]
Sorry to bother, but do you have an idea of when this might be included in a release? It'd be nice to no longer have hundreds of warnings pop up when running prettier-eslint-cli. :)

**Comment by zimme** [comment]
Sorry, been working 200% ish lately. Pushed a small change to get rid of the warning with version 4.7.1. This PR looks like a breaking change so don't. know when/if it will me merged. Will try to have a closer look next weekend

**Comment by ReDrUm** [comment]
No worries. I hadn't noticed 4.7.1. That suits my needs for now. Cheers.

**Pull request closed without merging**
