### PR TITLE
fix: Don't specify any jsxBracketSameLine parameter if none is specified

### LINKED ISSUE #428: Still reports "jsxBracketSameLine is deprecated." even when option is not used
- `prettier-eslint-cli` 5.0.1:
- `prettier` 2.5.0:
- `eslint` 7.11.0:

Relevant code/config.

```json
{
    "printWidth": 120,
    "tabWidth": 4,
    "bracketSameLine": false,
    "trailingComma": "es5"
}

```

What you did:
```
prettier-eslint "src/**/*.@(js|ts|jsx|tsx)" "cypress/**/*.@(ts|js)" --write --prettier-last
```

What happened:
I get a warning:
> jsxBracketSameLine is deprecated.

Reproduction:

-- paste your link here --

Problem description:
The program reports the deprecation of the `jsxBracketSameLine` option, which I'm aware of. As you can see from the prettier config above, there is no `jsxBracketSameLine` option being used.

Suggested solution:
This program should respect the config for user-installed prettier and not produce such extraneous warnings.

### PR DESCRIPTION
**Pull request by gwhitney**
By removing the default value for jsx-bracket-same-line (which is just
  `undefined` anyway), no option value at all for jsxBracketSameLine will
  be generated if none is specified. Then if a recent version of prettier
  is in use for which that option is deprecated, it won't complain.

  Resolves #428.

### CODE REVIEW

**Comment by chrisbobbe** [comment]
Hmm, it looks like the only files touched in https://github.com/prettier/prettier-eslint-cli/commit/04a8e04806db0b47e0282db3cebb1ea46dda4215 were `.all-contributorsrc` and `README.md`. I'm still seeing 

```
jsxBracketSameLine is deprecated.
```

with 6.0.1. Was there another change meant for this PR that got dropped?

**Comment by idahogurl** [comment]
Doh. @chrisbobbe I made the fix in my PR #431 because it was causing my test to fail. Because I got the way to fix it from this PR I decided to give the @gwhitney credit.

**Comment by chrisbobbe** [comment]
Ah, yeah—I realized that some time after I posted my comment. Seeing that a substantive change got merged, I went ahead and deleted my comment, thinking it'd be gone before it popped up on your radar. Sorry that it wasn't! 🙂

**Comment by chrisbobbe** [comment]
However, I'm still seeing

```
jsxBracketSameLine is deprecated.
```

with 6.0.1, and `prettier-eslint` 14.0.3—not yet quite sure why, or what's the right fix.

I find that I don't get that output if I remove the lines corresponding to [these](https://github.com/prettier/prettier-eslint/blob/v14.0.3/src/utils.js#L49-L53) in my `node_modules/prettier-eslint/dist/utils.js`. I intend to investigate more and hopefully report back tomorrow with my findings. 🙂

**Comment by chrisbobbe** [comment]
Ah, here's what I think is happening.

`react/jsx-closing-bracket-location` is active (not off) in my ESLint config. The specific setting (according to `eslint --print-config .eslintrc.yaml`) is:

```json
"react/jsx-closing-bracket-location": [
  "error",
  "line-aligned"
],
```

`prettier-eslint` (since https://github.com/prettier/prettier-eslint/commit/59ef52be61ccbd07a3ffc734ea1ecf49c5f46918) notices that ESLint setting and uses it to set an appropriate value for the Prettier setting `jsxBracketSameLine`. But Prettier deprecated that setting in https://github.com/prettier/prettier/commit/4992d972034b19acce9603a8444c95250cb1be8a (released in Prettier 2.4.0, it looks like), so I'm getting the deprecation warning.

In fact, for my specific choice of `react/jsx-closing-bracket-location` ('line-aligned'), `prettier-eslint` is choosing _`false`_ for `jsxBracketSameLine`, to turn the setting _off_. But, I guess understandably, newer Prettier prefers that people don't touch the setting at all, even to say "turn it off".

Should `prettier-eslint` solve this by no longer trying to set `jsxBracketSameLine`? https://github.com/prettier/prettier/commit/4992d972034b19acce9603a8444c95250cb1be8a proposed `bracketSameLine` as a replacement.

**Comment by idahogurl** [comment]
@chrisbobbe I'm thinking we use their proposed solution of `bracketSameLine`, `prettier-eslint` currently uses `^2.5.1` anyway as seen here https://github.com/prettier/prettier-eslint/blob/3746d674f3810d19156c3060c401adf536d999b8/package.json#L28

**Comment by chrisbobbe** [comment]
Great, that sounds good to me! Shall I make a PR?

**Comment by idahogurl** [comment]
@chrisbobbe That would be wonderful!

**Comment by chrisbobbe** [comment]
Just sent prettier/prettier-eslint#749 🙂

**Pull request merged**
